apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rg7rknzxj-nodejs 
  janus-idp.io/tekton: rg7rknzxj-nodejs
  backstage.io/kubernetes-id: rg7rknzxj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rg7rknzxj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  