apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rg7rknzxj-nodejs
  janus-idp.io/tekton: rg7rknzxj-nodejs
  backstage.io/kubernetes-id: rg7rknzxj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rg7rknzxj-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
